config/routes.rb
Rails.application.routes.draw do
  get    'sessions/new'
  get    '/' => "home#top"
  # Sessionsコントローラーのルーティングを設定
  get    '/login' => "sessions#new"
  post   '/login' => "sessions#create"
  delete '/logout' => "sessions#destroy"

  # resourcesを用いて、各種HTTPメソッドとコントローラー内のアクションを指すURLが対応づける.
  resources :tasks
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  # taskがuserに従属している
  belongs_to :user
  # 各カラムにバリデーションを追加する
  # category 空白でない 最大長20文字
  # content 空白でない 最大長20文字
  # user_id 空白でない
  validates :category, presence: true, length: { maximum: 20 }
  validates :content,  presence: true, length: { maximum: 50 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # ユーザーとタスクが 1対多 である関係を記述する。
  has_many :task
  # ハッシュ化したパスワードで認証できるようになる。
  has_secure_password
  # 有効なメールフォーマットを正規表現で検証する。
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  # 各カラムにバリデーションを追加する。
  # name: 空白でない 最大長20文字
  # email: 空白でない 最大長20文字 XXX@YYY.ZZZの形式 属性の値が重複しない
  validates :name,  presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 20 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #Sessionヘルパーモジュールをインクルードする
  include SessionsHelper
  #フラッシュメッセージのキーを許可する記述
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # ログインページを生成するアクション
  def new
  end

  # ログインするアクション
  def create
    # 入力として受け取ったemailからユーザーを取り出す.
    user = User.find_by(email: params[:session][:email].downcase)
    # 入力されたemailのユーザーが存在する && 入力されたパスワードがそのユーザーのものである場合
    if user && user.authenticate(params[:session][:password])
      # ログイン後のページへ遷移 cookiesに情報を追加する
      log_in user
      redirect_to tasks_path, success: "You are now logged!"
    else
      # そのままログインページへ
      flash.now[:danger] = 'Invalid email or password.'
      render :new
    end
  end

  # ログインしていたユーザーがログアウトするアクション
  # ログイン後はトップページに遷移する.
  def destroy
    #現在ログインしているユーザーをログアウトする　ログインしているユーザーを取得する
    log_out
    redirect_to '/'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # 投稿一覧を表示するアクション 作成時間の降順に表示する
  def index
    @tasks = Task.all.order(created_at: :desc)
  end

  # タスク追加画面のビューにアクセスするアクション
  def new
    @task = Task.new
  end

  # タスクの新規作成を行うアクション
  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path, success: "Successfully added the task!"
    else
      render :new
    end
  end

  # タスク編集画面のビューにアクセスするアクション
  def edit
    @task = Task.find_by(id:params[:id])
  end

  # タスクの編集を行うアクション
  def update
    @task = Task.find_by(id:params[:id])
    if @task.update(task_params)
      redirect_to tasks_path, success: "Successfully updated the task!"
    else
      render :edit
    end
  end

  # タスクの削除を行うアクション
  def destroy
    Task.find_by(id:params[:id]).destroy
    redirect_to tasks_path, success: "Deleted the task!"
  end

  # ストロングパラメータの定義
  # メソッドに変更を許可するカラム名を指定しておくことで、意図しないデータの保存を防ぐ
  # また、privateにすることでカプセル化する。
  private
  def task_params
    params.require(:task).permit(:category, :content).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ユーザ一覧を表示するアクション
  # SQLにおける N対1問題 を防ぐために、includesメソッドを使用する.
  def index
    # usersテーブルにアクセスすると同時に、関連するテーブルを取得する。
    @users = User.includes(:task)
  end

  # ユーザー新規作成のビューファイルにアクセスするアクション
  def new
    @user = User.new
  end

  # ユーザーを新規作成するアクション
  # 新規登録した場合でもログイン状態になるように、log_inメソッドに情報を渡す。
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to tasks_path, success:"Successful new registration!"
    else
      render :new
    end
  end

  # ユーザー編集のビューファイルにアクセスするアクション
  def edit
    @user = User.find_by(id:params[:id])
  end

  # ユーザーの編集を行うアクション
  # nameとemailのみ編集可能にする。
  def update
    @user = User.find_by(id:params[:id])
    if @user.update(name: user_params[:name], email: user_params[:email])
      redirect_to tasks_path, success:"Successful new registration!"
    else
      render :edit
    end
  end

  # ストロングパラメータの定義
  # メソッドに変更を許可するカラム名を指定しておくことで、意図しないデータの保存を防ぐ
  # また、privateにすることでカプセル化する。
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザー情報をcookiesに保存するメソッド
  def log_in(user)
    # 暗号化済のユーザーIDが一時的に保存される。
    session[:user_id] = user.id
  end

  # ログインしているユーザーを返すメソッド
  def current_user
    # cookieにuser_idが保存されていれば、ユーザー情報を取得する
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # ユーザーログインしているかを判別するメソッド
  def logged_in?
    # current_userが存在しているときに、trueを返す.
    current_user.present?
  end

  # ログアウトするメソッド
  def log_out
    # cookiesに保存されているuser_idを削除して、nilを代入することでログインしていない状態を表す。
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="top-main">
  <h1>Welcome to Todo Appication !</h1>
  <p>
    優先度はつけない !
    「やるべき事」だけを書く !
    詳しく書く !
  </p>
</div>

<div class="main-guide">
  <div class="intro-1">
    <h4>ユーザーごとにタスクを管理</h4>
    <img src="/assets/user.png" alt="画像1">
  </div>
  <div class="intro-2">
    <h4>シンプルを極めました</h4>
    <img src="/assets/index.png" alt="画像2">
  </div>
  <div class="intro-3">
    <h4>カテゴリ分類でわかりやすく</h4>
    <img src="/assets/category.png" alt="画像3">
  </div>
</div>

<div class="footer">
  <div class="text-center">
    <p class="text-muted">©︎2021 copyright</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApplication</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- application.scssとapplication.jsを読み込む. -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!--Bootstrapの導入-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</head>

<body>
  <!--ヘッダー メニュー欄を表示する。-->
  <header>
    <nav class="navbar navbar-expand{-sm|md|-lg|-xl|-xxl} navbar-expand-sm navbar-dark bg-dark mb-3">
      <a class="navbar-brand"><%= link_to("Do! Do!! Do!!!","/")%></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav4" role="navigation">
        <ul class="navbar-nav">
          <% if logged_in? %>
          <a class="nav-link"><%= link_to "#{current_user.name}さんようこそ", edit_user_path(current_user) %></a>
          <a class="nav-link"><%= link_to "タスク一覧", tasks_path %></a>
          <a class="nav-link"><%= link_to "ユーザー一覧", users_path %></a>
          <a class="nav-link"><%= link_to "ログアウト", logout_path, method: :delete %></a>
          <!-- ログインしていない時のメニュー欄 -->
          <% else %>
          <a class="nav-link"><%= link_to "新規登録", new_user_path %></a>
          <a class="nav-link"><%= link_to "ログイン", login_path %></a>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>
  <!--フラッシュメッセージのテンプレートを読み込む.-->
  <%= render "shared/flash" %>
  <%= yield %>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
</body>
</html>

app/views/shared/_flash.html.erb
<!-- フラッシュメッセージ用のテンプレートを作成 -->
<!-- content_tagを用いて、動的なフラッシュメッセージを生成する. -->
<% flash.each do |key,message| %>
  <%= content_tag(:p, message, class: "alert alert-#{key}")%>
<% end %>

app/views/shared/_task_message.html.erb
<!-- タスクの作成に失敗した時のエラーメッセージ -->
<!-- 部分テンプレートとしてまとめておく -->
<!-- エラーの個数と内容を表示する. -->
<% if @task.errors.any? %>
<div class="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(@task.errors.count, "error") %>
  </div>
  <ul>
    <% @task.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_user_message.html.erb
<!-- ユーザーの作成に失敗した時のエラーメッセージ -->
<!-- 部分テンプレートとしてまとめておく -->
<!-- エラーの個数と内容を表示する. -->
<% if @user.errors.any? %>
<div class="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(@user.errors.count, "error") %>
  </div>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/tasks/edit.html.erb
<!-- タスク編集のビューファイル -->
<div class="container">
  <div class="form-head">
    <h1>タスクの編集</h1>
  </div>

  <!-- ユーザー編集に失敗した時のエラーメッセージを表示する. -->
  <%= render "shared/task_message" %>
  <!-- form_withを用いて入力された情報を送信する 入力フォームに必要なHTMLを作成する。-->
  <!-- 生成されるHTML: <form action="/tasks" accept-charset="UTF-8" method="post"> -->
  <!-- 上記のHTMLより、入力されたデータはcreateアクションに渡される。 -->
  <%= form_with model: @task do |form| %>
  <form class="contact" action="index.html" method="post">
    <dl>
      <!--入力フォームの作成-->
      <dt><%= form.label :category, "カテゴリ"%></dt>
      <dd><%= form.text_field :category, :size=>"60"%></dd>
      <dt><%= form.label :content, "新規タスク"%></dt>
      <dd><%= form.text_field :content, :size=>"60"%></dd>
    </dl>
    <!--提出ボタンの作成-->
    <div class = "submit"><%= form.submit %></div>
  </form>
  <% end %>
  <!-- 戻るボタンの生成. link_toメソッドにBootstrapを適用する. -->
  <%= link_to(tasks_path) do %>
  <div class="d-grid gap-2 d-md-flex justify-content-md-center">
    <button type="button" class="btn btn-outline-primary">戻る</button>
  </div>
  <%end%>
</div>

app/views/tasks/index.html.erb
<!-- タスク一覧のビューファイル -->
<div class="text-center">
  <h1>タスク一覧</h1>
  <h3><%= l Time.now, format: :short %></h3>
  <%= link_to(new_task_path) do %>
  <button type="button" class="btn btn-info">Create Task</button>
  <%end%>
</div>
<!-- 表形式でタスクを出力する. -->
<table style="width: 80%" align="center" class="table table-striped">
  <thead>
    <tr>
      <th scope="col">カテゴリ名</th>
      <th scope="col">タスク名</th>
      <th scope="col">編集</th>
      <th scope="col">削除</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
    <!-- ログイン中のユーザーのidとタスクのuser_idが等しいものだけ、タスク一覧に表示する. -->
    <!-- すなわち、ログインユーザーごとにタスク一覧の表示が変わる. -->
    <% if current_user.id == task.user_id %>
    <tr>
      <!-- タスクのカテゴリと内容を表示する. -->
      <td style="width: 40%"><%= task.category %></td>
      <td style="width: 40%"><%= task.content %></td>

      <!-- 編集と削除ボタンを表示する. -->
      <td style="width: 10%">
        <%= link_to(edit_task_path(task)) do%>
        <button type="button" class="btn btn-primary">編集</button>
        <%end%>
      </td>
      <td style="width: 10%">
        <%= link_to(task_path(task), method: :delete, data: { confirm: "本当に削除しますか？" }) do %>
        <button type="button" class="btn btn-danger">削除</button>
        <%end%>
      </td>
    </tr>
    <% end %>
  </tbody>
  <% end %>
</table>

app/views/tasks/new.html.erb
<!-- タスク新規作成のビューファイル -->
<div class="container">
  <div class="form-head">
    <h1>新規タスク</h1>
  </div>

  <!-- ユーザー新規登録が失敗した時のエラーメッセージ表示-->
  <%= render "shared/task_message" %>
  <!-- form_withを用いて入力された情報を送信する 入力フォームに必要なHTMLを作成する。-->
  <!-- 生成されるHTML: <form action="/tasks" accept-charset="UTF-8" method="post"> -->
  <!-- 上記のHTMLより、入力されたデータはcreateアクションに渡される。 -->
  <%= form_with model: @task do |form| %>
  <form class="contact" action="index.html" method="post">
    <dl>
      <!--入力フォームの作成-->
      <dt><%= form.label :category, "カテゴリ"%></dt>
      <dd><%= form.text_field :category, :size=>"60"%></dd>
      <dt><%= form.label :content, "新規タスク"%></dt>
      <dd><%= form.text_field :content, :size=>"60" %></dd>
    </dl>
    <!--提出ボタンの作成-->
    <div class = "submit"><%= form.submit %></div>
  </form>
  <% end %>
  <!-- 戻るボタンの生成. link_toメソッドにBootstrapを適用する. -->
  <%= link_to(tasks_path) do %>
  <div class="d-grid gap-2 d-md-flex justify-content-md-center">
    <button type="button" class="btn btn-outline-primary">戻る</button>
  </div>
  <%end%>
</div>

app/views/users/edit.html.erb
<!-- ユーザー編集のビューファイル -->
<div class="container">
  <div class="form-head">
    <h1>ユーザーの編集</h1>
  </div>

  <!-- ユーザー編集に失敗した時のエラーメッセージを表示する. -->
  <%= render "shared/user_message" %>
  <!-- ユーザー情報をコントローラーに渡す. -->
  <%= form_with model: @user do |form| %>
  <form class="contact" action="index.html" method="post">
    <dl>
      <dt><%= form.label :name ,"ユーザー名"%></dt>
      <dd><%= form.text_field :name ,:size=>"60"%></dd>
      <dt><%= form.label :email ,"Email"%></dt>
      <dd><%= form.text_field :email ,:size=>"60"%></dd>
    </dl>
    <div class = "submit"><%= form.submit %></div>
  </form>
  <% end %>

  <%= link_to(tasks_path) do %>
  <div class="d-grid gap-2 d-md-flex justify-content-md-center">
    <button type="button" class="btn btn-outline-primary">戻る</button>
  </div>
  <%end%>
</div>

app/views/users/index.html.erb
<!-- ユーザー一覧を表示するビューファイル -->
<div class="text-center">
  <h1>List of user</h1>
  <p>The name of the user who is logged in is colored.</p>
</div>

<!-- ユーザー名を一覧で表示する. -->
<div class="user-list">
  <ul class="list-group mx-auto" style="width: 80%" align="center">
    <% @users.each do |user| %>
    <!-- ログイン中のユーザーのみ色を変更する処理. -->
    <% if current_user == user %>
    <li class="list-group-item active" aria-current="true"><%= user.name %></li>
    <% else %>
    <li class="list-group-item"><%= user.name %></li>
    <% end %>
    <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<!-- ユーザー新規登録のビューファイル -->
<div class="container">
  <div class="form-head">
    <h1>ユーザーの新規登録</h1>
  </div>

  <!-- ユーザー新規登録が失敗した時のエラーメッセージ表示-->
  <%= render "shared/user_message" %>
  <!-- form_withを用いて入力された情報を送信する 入力フォームに必要なHTMLを作成する。-->
  <%= form_with model: @user do |form| %>
  <form class="contact" action="index.html" method="post">
    <dl>
      <dt><%= form.label :name, "ユーザー名"%></dt>
      <dd><%= form.text_field :name, :size=>"60"%></dd>
      <dt><%= form.label :email, "Email"%></dt>
      <dd><%= form.text_field :email, :size=>"60"%></dd>
      <dt><%= form.label :password, "パスワード"%></dt>
      <dd><%= form.password_field :password, :size=>"60"%></dd>
      <dt><%= form.label :password_confirmation, "パスワード(確認)"%></dt>
      <dd><%= form.password_field :password_confirmation, :size=>"60"%></dd>
    </dl>
    <div class = "submit"><%= form.submit %></div>
  </form>
  <% end %>

  <!-- 戻る ボタンの生成 トップページに遷移する-->
  <%= link_to('/') do %>
  <div class="d-grid gap-2 d-md-flex justify-content-md-center">
    <button type="button" class="btn btn-outline-primary">戻る</button>
  </div>
  <%end%>
</div>